### PR TITLE
Added loading environment variables from .env file in config.py.

### PR DESCRIPTION
**Pull request by ArturM94**

### CODE REVIEW

**Comment by VanyaDNDZ** [comment]
If you bring such library please add howto part to the README

**Comment by ArturM94** [comment]
@VanyaDNDZ 
Howto like that: `pip install -r src/app/requirements.txt` ?

**Comment by ArturM94** [comment]
Or you mean description about creating `.env` file for local use?

**Comment by VanyaDNDZ** [comment]
Can you describe creating `.env` file

**Comment by ArturM94** [comment]
Yes. I'll do that.

**Pull request merged**
